---
- name: Prepare file servers
  hosts: fileservers
  roles:
    - name: setup-zfs
      vars:
        zpool_name: data
        zpool_disks: /dev/vdb
        filesystems:
          - name: cluster-1
            clients:
              - 10.255.1.0/24
...