---
- name: Setup my temporary SSH key
  hosts: localhost
  connection: local
  tasks:
    - name: Create an SSH key pair
      openssh_keypair:
        path: actions
        type: ed25519

    - name: Sign the public key
      shell: vault write -field=signed_key ssh/sign/sysuser-role public_key=@actions.pub > actions-cert.pub
      args:
        creates: actions-cert.pub

- name: Setup my control machine
  hosts: my_machines

  tasks:
    - name: Install packages
      package:
        name: '{{ item }}'
      become: true
      loop:
        - tmux
        - vim
        - git

    - name: Update my tmux.conf
      copy:
        src: tmux.conf
        dest: ~/.tmux.conf

    - name: Update my gitconfig
      copy:
        src: gitconfig
        dest: ~/.gitconfig

    - name: Update my vimrc
      copy:
        src: vimrc
        dest: ~/.vimrc

- name: Post-playbook clean up
  hosts: localhost
  connection: local
  tasks:
    - name: Remove signed key
      file:
        path: actions-cert.pub
        state: absent
