#!/usr/local/bin/ansible-playbook -t untagged
---
- name: Setup my private key
  hosts: localhost
  connection: local

  tasks:
    - name: Setup private key
      include_tasks: ssh.yaml
      vars:
        aws_region: us-east-1
        my_public_keys: https://github.com/tlhakhan.keys
      tags: ssh

    - name: Setup preferences
      include_tasks: prefs.yaml
      tags: prefs
