- name: Setup SSH CA signed keys
  hosts: localhost
  connection: local
  gather_facts: false

  tasks:
    - debug:
        msg: '{{ playbook_dir }}'

    - name: Create an SSH key pair
      openssh_keypair:
        path: '{{ playbook_dir }}/actions'
        type: ed25519

    - name: Sign the public key
      shell: 'vault write -field=signed_key ssh/sign/sysuser-role public_key=@{{ playbook_dir }}/actions.pub > {{ playbook_dir }}/actions-cert.pub'
      args:
        creates: '{{ playbook_dir }}/actions-cert.pub'
