- name: Create an SSH key pair
  openssh_keypair:
    path: actions
    type: ed25519
  delegate_to: localhost
  connection: local

- name: Sign the public key
  shell: vault write -field=signed_key ssh/sign/sysuser-role public_key=@actions.pub > actions-cert.pub
  args:
    creates: actions-cert.pub
  delegate_to: localhost
  connection: local
