control_plane_endpoint_name: cluster-endpoint
control_plane_endpoint_address: 127.0.0.1
pod_network_cidr: 10.253.0.0/16
service_network_cidr: 10.254.0.0/16

# keepalived
enable_keepalived: False
keepalived_router_id: 100
keepalived_cluster_password: clusterpass

# bootstrap node
skip_phase_mark_control_plane: False