- name: Create partition on the disk
  parted:
    device: "{{ disk_device }}"
    number: 1
    state: present
    part_type: primary
    fs_type: ext4
    resize: yes

- name: Create ext4 filesystem on the partition
  filesystem:
    fstype: ext4
    dev: "{{ disk_device }}1"

- name: Create mount point
  file:
    path: "{{ mount_point }}"
    state: directory

- name: Mount partition to /data
  mount:
    path: "{{ mount_point }}"
    src: "{{ disk_device }}1"
    fstype: ext4
    state: mounted

- name: Ensure mount persists on reboot
  mount:
    path: "{{ mount_point }}"
    src: "{{ disk_device }}1"
    fstype: ext4
    state: present
