- name: Setup hypervisors
  hosts: hypervisors

  tasks:
    - name: Update OS physical volume
      lvg:
        vg: ubuntu-vg
        pvs: "{{ root_disks | join(',') }}"
        pvresize: True

    - name: Update OS logical vol
      lvol:
        vg: ubuntu-vg
        lv: ubuntu-lv
        size: 95%PVS
        resizefs: True

    - name: Update /etc/default/grub
      lineinfile:
        path: /etc/default/grub
        regexp: '^GRUB_CMDLINE_LINUX='
        line: 'GRUB_CMDLINE_LINUX="net.ifnames=0 biosdevname=0 amd_iommu=on amd_iommu=pt"'
      notify:
        - update grub
        - reboot system
      when: has_nvidia_gpu == False

    - name: Update /etc/default/grub for GPU pass through
      lineinfile:
        path: /etc/default/grub
        regexp: '^GRUB_CMDLINE_LINUX='
        line: "GRUB_CMDLINE_LINUX=\"net.ifnames=0 biosdevname=0 amd_iommu=on amd_iommu=pt video=efifb:off pcie_acs_override=downstream,multifunction vfio-pci.ids={{ gpu_pci_ids | join(',') }} vfio-pci.disable_vga=1\""
      notify:
        - update grub
        - reboot system
      when: has_nvidia_gpu == True

    - name: Blacklist nvidia modules
      copy:
        dest: /etc/modprobe.d/no-nvidia.conf
        content: |-
          blacklist nvidia
          blacklist nvidia_drm
          blacklist nvidia_uvm
          blacklist nvidia_modeset
          blacklist nvidiafb
          blacklist nouveau
      notify: update initramfs
      when: has_nvidia_gpu == True

    - name: Create /etc/apparmor.d/abstractions/libvirt-qemu.d
      file:
        path: /etc/apparmor.d/abstractions/libvirt-qemu.d
        state: directory

    - name: Update apparmor for libvirt-qemu extra paths
      copy:
        content: |-
          /var/lib/libvirt/images/* rwk,
          /var/lib/libvirt/machines/* rwk,
        dest: /etc/apparmor.d/abstractions/libvirt-qemu.d/libvirt-qemu-extras

  handlers:
    - name: update grub
      command: update-grub

    - name: update initramfs
      command: update-initramfs -u

    - name: reboot system
      reboot:
        reboot_timeout: 300