- name: Clean-up SSH keys
  hosts: localhost
  connection: local
  gather_facts: false

  tasks:
    - name: Remove keys
      file:
        path: '{{ item }}'
        state: absent
      loop:
        - actions
        - actions.pub
        - actions-cert.pub
