---
- name: Setup my Kubernetes development cluster
  hosts: my_k8s_dev

  vars:
    kubernetes_control_plane_endpoint_name: homelab-k8s-dev.tenzin.io
    kubernetes_control_plane_endpoint_address: 192.168.200.229

  roles:
    - name: setup-kubernetes
      become: true
      when: "'control-plane' in group_names"

  tasks:
    - name: Upload the admin.conf file
      community.hashi_vault.vault_write:
        path: secrets/data/kubeconfig/homelab-k8s-dev
        data:
          data:
            kubernetes_admin_conf: "{{ kubernetes_admin_conf['content'] | b64decode }}"
      delegate_to: localhost
      connection: local
      when: kubernetes_admin_conf is defined and kubernetes_admin_conf.content is defined

...
