name: 01-hypervisor-setup/vhost

on:
  workflow_dispatch:
    inputs:
      environment:
        type: environment

env:
  WORKFLOW_DIR: 01-hypervisor-setup/vhost

jobs:
  terraform:
    environment: ${{ inputs.environment }}
    runs-on: [ubuntu-latest]
    permissions:
      contents: read
      id-token: write
    defaults:
      run:
        working-directory: ${{ env.WORKFLOW_DIR }}

    steps:
      - uses: actions/checkout@v3

      - uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "~1.9"

      - name: Get Vault token
        id: vault-secrets
        uses: hashicorp/vault-action@v2
        with:
          url: https://vault.tenzin.io
          role: tenzin-io.ansible-playbooks
          method: jwt
          exportToken: true
          secrets: |-
            secrets/data/github-actions/tailscale tailscale_oauth_client_id | TS_OAUTH_CLIENT_ID ;
            secrets/data/github-actions/tailscale tailscale_oauth_client_secret | TS_OAUTH_CLIENT_SECRET ;
            secrets/data/platform-setup/automation-ssh-user/tenzin-bot SSH_PRIVATE_KEY_ED25519 | SSH_PRIVATE_KEY_ED25519 ;

      - name: Tailscale connection
        uses: tailscale/github-action@v2
        with:
          oauth-client-id: ${{ steps.vault-secrets.outputs.TS_OAUTH_CLIENT_ID }}
          oauth-secret: ${{ steps.vault-secrets.outputs.TS_OAUTH_CLIENT_SECRET }}
          tags: tag:ci

      - name: Setup secrets
        run: |-
          # make ~/.ssh folder
          test -e ~/.ssh || mkdir ~/.ssh

          # setup secrets
          cat <<EOF > tenzin-bot.key
          ${{ steps.vault-secrets.outputs.SSH_PRIVATE_KEY_ED25519 }}
          EOF
          chmod 0600 tenzin-bot.key
          cp tenzin-bot.key ~/.ssh/id_ed25519

          # setup ssh proxyjump config
          cat <<EOF > ~/.ssh/config
          StrictHostKeyChecking no
          EOF

      - name: Run Terraform Init
        run: terraform init
        
      - name: Run Terraform Validate
        run: terraform validate

      - name: Terraform apply
        run: terraform apply -auto-approve
...
