name: Run playbook

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: [homelab, v1]

    steps:
      - uses: actions/checkout@v3

      - name: Install Ansible
        run: |
          sudo apt-get update
          sudo apt-get install -y python3-pip
          pip install --upgrade pip
          pip install --upgrade ansible
          ansible-galaxy collection install --timeout 180 community.general

