name: Run playbook

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: [homelab, v1]
    permission:
      contents: read
      id-token: write

    steps:
      - uses: actions/checkout@v3

      - name: Install Ansible
        run: |
          sudo apt-get update
          sudo apt-get install -y python3-pip
          pip install --upgrade pip
          pip install --upgrade ansible
          ansible-galaxy collection install --timeout 180 community.general

      - name: Generate a temporary SSH keypair
        run: |
          ssh-keygen -t ed25519 -f actions

      - name: Get Vault token
        uses: hashicorp/vault-action@v2
        with:
          url: https://vault.tenzin.io
          role: ${{ vars.VAULT_ROLE_TO_ASSUME }}
          method: jwt
          exportToken: true
      
      - name: Debug
        run: env
