name: Reset homelab-k8s-dev

on:
  workflow_dispatch:

env:
  VAULT_ADDR: https://vault.tenzin.io
  WORKFLOW_DIR: dev-k8s

jobs:
  ansible:
    runs-on: [ubuntu-latest]
    permissions:
      contents: read
      id-token: write
    defaults:
      run:
        working-directory: ${{ env.WORKFLOW_DIR }}

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Get Vault token
        id: vault-secrets
        uses: hashicorp/vault-action@v2
        with:
          url: https://vault.tenzin.io
          role: ${{ vars.VAULT_ROLE_TO_ASSUME }}
          method: jwt
          exportToken: true
          secrets: |
            secret/data/tailscale/github-actions client_id | TS_OAUTH_CLIENT_ID
            secret/data/tailscale/github-actions client_secret | TS_OAUTH_CLIENT_SECRET

      - name: Tailscale connection
        uses: tailscale/github-action@v2
        with:
          oauth-client-id: ${{ steps.vault-secrets.outputs.TS_OAUTH_CLIENT_ID }}
          oauth-secret: ${{ steps.vault-secrets.outputs.TS_OAUTH_CLIENT_SECRET }}
          tags: tag:ci


      - name: Setup SSH key
        run: |
          ssh-keygen -t ed25519 -f ${HOME}/.ssh/id_ed25519 -N ""
          chmod 0600 ${HOME}/.ssh/id_ed25519
          vault write -field=signed_key ssh/sign/sysuser-role public_key=@${HOME}/.ssh/id_ed25519.pub > ${HOME}/.ssh/id_ed25519-cert.pub
          ssh-keygen -Lf ${HOME}/.ssh/id_ed25519-cert.pub

      - name: Run playbook
        run: ansible-playbook reset-k8s-nodes.yaml

      - name: Clean up SSH key
        run: |
          test -e ${HOME}/.ssh/actions && rm ${HOME}/.ssh/id_ed25519
          test -e ${HOME}/.ssh/actions.pub && rm ${HOME}/.ssh/id_ed25519.pub
          test -e ${HOME}/.ssh/actions-cert.pub && rm ${HOME}/.ssh/id_ed25519-cert.pub

...
