name: Setup fileservers

on:
  workflow_dispatch:

env:
  VAULT_ADDR: https://vault.tenzin.io

jobs:
  ansible:
    runs-on: [homelab, v1]
    permissions:
      contents: read
      id-token: write

    steps:
      - uses: actions/checkout@v3

      - name: Get Vault token
        uses: hashicorp/vault-action@v2
        with:
          url: https://vault.tenzin.io
          role: ${{ vars.VAULT_ROLE_TO_ASSUME }}
          method: jwt
          exportToken: true

      - name: Ping zfs-1.tenzin.io
        run: ping -w1 -c4 zfs-1.tenzin.io

      - name: Run playbook
        run: ansible-playbook -vvv setup-fileservers.yaml
