name: 02-vm-provisioner/vhost-1

on:
  workflow_dispatch:

env:
  WORKFLOW_DIR: 02-vm-provisioner/vhost-1

jobs:
  terraform:
    runs-on: [ubuntu-latest]
    permissions:
      contents: read
      id-token: write
    defaults:
      run:
        working-directory: ${{ env.WORKFLOW_DIR }}

    steps:
      - uses: actions/checkout@v3
     
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::130900203380:role/tenzin-io.ansible-playbooks
          aws-region: us-east-1

      - name: Get Vault token
        id: vault-secrets
        uses: hashicorp/vault-action@v2
        with:
          url: https://vault.tenzin.io
          role: tenzin-io.ansible-playbooks
          method: jwt
          exportToken: true
          secrets: |
            secrets/data/github-actions/tailscale tailscale_oauth_client_id | TS_OAUTH_CLIENT_ID ;
            secrets/data/github-actions/tailscale tailscale_oauth_client_secret | TS_OAUTH_CLIENT_SECRET ;
            secrets/data/ansible-playbooks/ansible-ssh-user/ansible SSH_PRIVATE_KEY_ED25519 | SSH_PRIVATE_KEY_ED25519 ;

      - name: Tailscale connection
        uses: tailscale/github-action@v2
        with:
          oauth-client-id: ${{ steps.vault-secrets.outputs.TS_OAUTH_CLIENT_ID }}
          oauth-secret: ${{ steps.vault-secrets.outputs.TS_OAUTH_CLIENT_SECRET }}
          tags: tag:ci

      - name: Setup secrets
        run: |

          # make ~/.ssh folder
          test -e ~/.ssh || mkdir ~/.ssh

          # setup ansible.key
          cat <<EOF > ansible.key
          ${{ steps.vault-secrets.outputs.SSH_PRIVATE_KEY_ED25519 }}
          EOF
          chmod 0600 ansible.key

          # setup ssh config
          cat <<EOF > ~/.ssh/config
          StrictHostKeyChecking no

          Host bastion
            User root
            Hostname tenzins-pi
          
          Host vhost-1.lan
            ProxyJump bastion
            IdentityFile /dev/null
          EOF

      - name: Run Terraform Init
        run: terraform init
        
      - name: Run Terraform Format
        run: terraform fmt -check
        
      - name: Run Terraform Validate
        run: terraform validate

      - name: Terraform apply
        run: terraform apply -auto-approve

      - name: Clean up secrets
        run: |
          test -e ansible.key && rm -f ansible.key

...
